#!/usr/bin/env python3
"""
H-Tree vs X-Tree Comparison Report Generator

Reads CTS comparison JSON and generates:
- Text report (cts_comparison.txt)
- Visualization charts (cts_tree_comparison.png)
"""

import json
import argparse
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from typing import Dict, Any


def generate_text_report(comparison_data: Dict[str, Any], output_path: str):
    """
    Generate text report comparing H-Tree vs X-Tree.
    
    Args:
        comparison_data: Dictionary from cts_comparison.json
        output_path: Path to save text report
    """
    htree = comparison_data['htree']
    xtree = comparison_data['xtree']
    comp = comparison_data['comparison']
    
    with open(output_path, 'w') as f:
        f.write("=" * 70 + "\n")
        f.write("CTS Tree Comparison Report: H-Tree vs X-Tree\n")
        f.write("=" * 70 + "\n\n")
        
        f.write("METRICS SUMMARY\n")
        f.write("-" * 70 + "\n")
        f.write(f"{'Metric':<25} {'H-Tree':<20} {'X-Tree':<20}\n")
        f.write("-" * 70 + "\n")
        f.write(f"{'Clock Skew (ns)':<25} {htree['skew']:<20.3f} {xtree['skew']:<20.3f}\n")
        f.write(f"{'Max Delay (ns)':<25} {htree['max_delay']:<20.3f} {xtree['max_delay']:<20.3f}\n")
        f.write(f"{'Min Delay (ns)':<25} {htree['min_delay']:<20.3f} {xtree['min_delay']:<20.3f}\n")
        f.write(f"{'Total Wirelength (um)':<25} {htree['total_wirelength']:<20.1f} {xtree['total_wirelength']:<20.1f}\n")
        f.write(f"{'Avg Wirelength (um)':<25} {htree['avg_wirelength']:<20.1f} {xtree['avg_wirelength']:<20.1f}\n")
        f.write(f"{'Buffer Count':<25} {htree['buffer_count']:<20} {xtree['buffer_count']:<20}\n")
        f.write(f"{'Avg Path Length':<25} {htree['avg_path_length']:<20.2f} {xtree['avg_path_length']:<20.2f}\n")
        f.write(f"{'Number of Sinks':<25} {htree['num_sinks']:<20} {xtree['num_sinks']:<20}\n")
        f.write("-" * 70 + "\n\n")
        
        f.write("COMPARISON\n")
        f.write("-" * 70 + "\n")
        f.write(f"Skew Difference: {comp['skew_diff']:.3f} ns ")
        if comp['skew_diff'] < 0:
            f.write("(H-Tree has lower skew)\n")
        else:
            f.write("(X-Tree has lower skew)\n")
        
        f.write(f"Wirelength Difference: {comp['wirelength_diff']:.1f} um ")
        if comp['wirelength_diff'] < 0:
            f.write("(H-Tree has lower wirelength)\n")
        else:
            f.write("(X-Tree has lower wirelength)\n")
        
        f.write(f"Buffer Count Difference: {comp['buffer_diff']} ")
        if comp['buffer_diff'] < 0:
            f.write("(H-Tree uses fewer buffers)\n")
        else:
            f.write("(X-Tree uses fewer buffers)\n")
        f.write("-" * 70 + "\n\n")
        
        f.write("RECOMMENDATIONS\n")
        f.write("-" * 70 + "\n")
        f.write(f"Best for Clock Skew: {comp['skew_winner']}\n")
        f.write(f"Best for Wirelength: {comp['wirelength_winner']}\n")
        f.write("\n")
        
        # Overall recommendation
        if comp['skew_winner'] == comp['wirelength_winner']:
            f.write(f"Overall Recommendation: {comp['skew_winner']} performs better in both metrics.\n")
        else:
            f.write("Overall Recommendation: Trade-off between metrics.\n")
            f.write(f"  - Use {comp['skew_winner']} if clock skew is the primary concern.\n")
            f.write(f"  - Use {comp['wirelength_winner']} if wirelength/power is the primary concern.\n")
        f.write("\n")
        
        f.write("=" * 70 + "\n")
        f.write("Report generated by comparison_report.py\n")
        f.write("=" * 70 + "\n")


def generate_visualization(comparison_data: Dict[str, Any], output_path: str):
    """
    Generate visualization charts comparing H-Tree vs X-Tree.
    
    Args:
        comparison_data: Dictionary from cts_comparison.json
        output_path: Path to save PNG file
    """
    htree = comparison_data['htree']
    xtree = comparison_data['xtree']
    comp = comparison_data['comparison']
    
    # Create figure with subplots - better layout
    fig = plt.figure(figsize=(16, 10))
    gs = fig.add_gridspec(2, 3, hspace=0.3, wspace=0.3)
    fig.suptitle('CTS Tree Comparison: H-Tree vs X-Tree', fontsize=18, fontweight='bold', y=0.98)
    
    # 1. Skew comparison (bar chart) - top left
    ax1 = fig.add_subplot(gs[0, 0])
    skew_values = [htree['skew'], xtree['skew']]
    bars = ax1.bar(['H-Tree', 'X-Tree'], skew_values,
                   color=['#4169E1', '#FF6347'], alpha=0.8, width=0.6)
    ax1.set_ylabel('Clock Skew (ns)', fontsize=12, fontweight='bold')
    ax1.set_title('Clock Skew Comparison\n(Lower is Better)', fontsize=13, fontweight='bold', pad=10)
    ax1.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # Add value labels on bars with better formatting
    for i, (bar, val) in enumerate(zip(bars, skew_values)):
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height + height*0.02,
                f'{val:.3f} ns',
                ha='center', va='bottom', fontsize=11, fontweight='bold')
    
    # Highlight winner with green border
    winner_idx = 0 if comp['skew_winner'] == 'H-Tree' else 1
    bars[winner_idx].set_edgecolor('green')
    bars[winner_idx].set_linewidth(4)
    bars[winner_idx].set_hatch('///')
    
    # Add percentage difference
    diff_pct = abs(comp['skew_diff'] / max(skew_values) * 100)
    ax1.text(0.5, 0.95, f'Difference: {abs(comp["skew_diff"]):.3f} ns ({diff_pct:.1f}%)',
            transform=ax1.transAxes, ha='center', va='top',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8), fontsize=10)
    
    # 2. Wirelength comparison (bar chart) - top middle
    ax2 = fig.add_subplot(gs[0, 1])
    wirelength_values = [htree['total_wirelength'], xtree['total_wirelength']]
    bars2 = ax2.bar(['H-Tree', 'X-Tree'], wirelength_values,
                    color=['#4169E1', '#FF6347'], alpha=0.8, width=0.6)
    ax2.set_ylabel('Total Wirelength (μm)', fontsize=12, fontweight='bold')
    ax2.set_title('Total Wirelength Comparison\n(Lower is Better)', fontsize=13, fontweight='bold', pad=10)
    ax2.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # Add value labels
    for i, (bar, val) in enumerate(zip(bars2, wirelength_values)):
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height + height*0.01,
                f'{val/1000:.1f}K μm',
                ha='center', va='bottom', fontsize=11, fontweight='bold')
    
    # Highlight winner
    winner_idx = 0 if comp['wirelength_winner'] == 'H-Tree' else 1
    bars2[winner_idx].set_edgecolor('green')
    bars2[winner_idx].set_linewidth(4)
    bars2[winner_idx].set_hatch('///')
    
    # Add percentage difference
    diff_pct = abs(comp['wirelength_diff'] / max(wirelength_values) * 100)
    ax2.text(0.5, 0.95, f'Difference: {abs(comp["wirelength_diff"]):.0f} μm ({diff_pct:.2f}%)',
            transform=ax2.transAxes, ha='center', va='top',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8), fontsize=10)
    
    # 3. Buffer count comparison (bar chart) - top right
    ax3 = fig.add_subplot(gs[0, 2])
    buffer_values = [htree['buffer_count'], xtree['buffer_count']]
    bars3 = ax3.bar(['H-Tree', 'X-Tree'], buffer_values,
                    color=['#4169E1', '#FF6347'], alpha=0.8, width=0.6)
    ax3.set_ylabel('Number of Buffers', fontsize=12, fontweight='bold')
    ax3.set_title('Buffer Count Comparison\n(Lower is Better)', fontsize=13, fontweight='bold', pad=10)
    ax3.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # Add value labels
    for i, (bar, val) in enumerate(zip(bars3, buffer_values)):
        height = bar.get_height()
        ax3.text(bar.get_x() + bar.get_width()/2., height + 0.5,
                f'{int(val)}',
                ha='center', va='bottom', fontsize=12, fontweight='bold')
    
    # Highlight winner
    if comp['buffer_diff'] != 0:
        winner_idx = 0 if comp['buffer_diff'] < 0 else 1
        bars3[winner_idx].set_edgecolor('green')
        bars3[winner_idx].set_linewidth(4)
        bars3[winner_idx].set_hatch('///')
    
    # Add difference
    ax3.text(0.5, 0.95, f'Difference: {abs(comp["buffer_diff"])} buffers',
            transform=ax3.transAxes, ha='center', va='top',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8), fontsize=10)
    
    # 4. Delay distribution histogram - bottom left (span 2 columns)
    ax4 = fig.add_subplot(gs[1, :2])
    
    # Extract delays from sink paths
    htree_delays = [path['delay'] for path in htree.get('sink_paths', [])]
    xtree_delays = [path['delay'] for path in xtree.get('sink_paths', [])]
    
    if htree_delays and xtree_delays:
        bins = np.linspace(min(min(htree_delays), min(xtree_delays)),
                          max(max(htree_delays), max(xtree_delays)), 30)
        ax4.hist(htree_delays, bins=bins, alpha=0.6, label='H-Tree', 
                color='#4169E1', edgecolor='black', linewidth=0.5)
        ax4.hist(xtree_delays, bins=bins, alpha=0.6, label='X-Tree',
                color='#FF6347', edgecolor='black', linewidth=0.5)
        ax4.axvline(htree['max_delay'], color='#4169E1', linestyle='--', linewidth=2, label='H-Tree Max')
        ax4.axvline(htree['min_delay'], color='#4169E1', linestyle=':', linewidth=2, label='H-Tree Min')
        ax4.axvline(xtree['max_delay'], color='#FF6347', linestyle='--', linewidth=2, label='X-Tree Max')
        ax4.axvline(xtree['min_delay'], color='#FF6347', linestyle=':', linewidth=2, label='X-Tree Min')
        ax4.set_xlabel('Path Delay (ns)', fontsize=12, fontweight='bold')
        ax4.set_ylabel('Number of DFFs', fontsize=12, fontweight='bold')
        ax4.set_title('Delay Distribution Across All DFFs', fontsize=13, fontweight='bold', pad=10)
        ax4.legend(loc='upper right', fontsize=9)
        ax4.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    # 5. Summary metrics table - bottom right
    ax5 = fig.add_subplot(gs[1, 2])
    ax5.axis('off')
    
    # Create summary table
    summary_data = [
        ['Metric', 'H-Tree', 'X-Tree', 'Winner'],
        ['Skew (ns)', f"{htree['skew']:.3f}", f"{xtree['skew']:.3f}", comp['skew_winner']],
        ['Wirelength (Kμm)', f"{htree['total_wirelength']/1000:.1f}", 
         f"{xtree['total_wirelength']/1000:.1f}", comp['wirelength_winner']],
        ['Buffers', f"{htree['buffer_count']}", f"{xtree['buffer_count']}", 
         'H-Tree' if comp['buffer_diff'] < 0 else 'X-Tree' if comp['buffer_diff'] > 0 else 'Tie'],
        ['Max Delay (ns)', f"{htree['max_delay']:.3f}", f"{xtree['max_delay']:.3f}", 
         'H-Tree' if htree['max_delay'] < xtree['max_delay'] else 'X-Tree'],
        ['Min Delay (ns)', f"{htree['min_delay']:.3f}", f"{xtree['min_delay']:.3f}",
         'H-Tree' if htree['min_delay'] < xtree['min_delay'] else 'X-Tree'],
    ]
    
    table = ax5.table(cellText=summary_data[1:], colLabels=summary_data[0],
                     cellLoc='center', loc='center',
                     colWidths=[0.3, 0.2, 0.2, 0.3])
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 2)
    
    # Style header row
    for i in range(4):
        table[(0, i)].set_facecolor('#4A90E2')
        table[(0, i)].set_text_props(weight='bold', color='white')
    
    # Highlight winner cells
    for i in range(1, len(summary_data)):
        winner_col = summary_data[i][3]
        if winner_col == 'H-Tree':
            table[(i, 1)].set_facecolor('#90EE90')
        elif winner_col == 'X-Tree':
            table[(i, 2)].set_facecolor('#FFB6C1')
    
    ax5.set_title('Summary Comparison', fontsize=13, fontweight='bold', pad=10)
    
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Visualization saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate H-Tree vs X-Tree comparison report and visualization'
    )
    parser.add_argument('--input', type=str, default=None,
                        help='Path to cts_comparison.json file')
    parser.add_argument('--output-txt', type=str, default=None,
                        help='Path to save text report (default: cts_comparison.txt)')
    parser.add_argument('--output-png', type=str, default=None,
                        help='Path to save visualization (default: cts_tree_comparison.png)')
    parser.add_argument('--design', type=str, default=None,
                        help='Design name (e.g., 6502) - used to construct default paths')
    
    args = parser.parse_args()
    
    # Handle default paths
    if args.design:
        if args.input is None:
            args.input = f'build/{args.design}/cts_comparison.json'
        if args.output_txt is None:
            args.output_txt = f'build/{args.design}/cts_comparison.txt'
        if args.output_png is None:
            args.output_png = f'build/{args.design}/cts_tree_comparison.png'
    else:
        if args.input is None:
            args.input = 'cts_comparison.json'
        if args.output_txt is None:
            args.output_txt = 'cts_comparison.txt'
        if args.output_png is None:
            args.output_png = 'cts_tree_comparison.png'
    
    # Load comparison data
    print(f"Loading comparison data from: {args.input}")
    with open(args.input, 'r') as f:
        comparison_data = json.load(f)
    
    # Generate text report
    print(f"Generating text report...")
    generate_text_report(comparison_data, args.output_txt)
    print(f"✓ Text report saved to: {args.output_txt}")
    
    # Generate visualization
    print(f"Generating visualization...")
    generate_visualization(comparison_data, args.output_png)
    print(f"✓ Visualization saved to: {args.output_png}")
    
    print("\n=== Report Generation Complete ===")
    print(f"Text report: {args.output_txt}")
    print(f"Visualization: {args.output_png}")


if __name__ == '__main__':
    main()

